#!/usr/local/sbin/charm-env python3

from lib_sysconfig import check_update_grub

from charmhelpers.core import hookenv


def main():
    _, message = check_update_grub()
    hookenv.action_set({"message": message})

if __name__ == "__main__":
    main()
