#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv
from lib_sysconfig import clear_notification


def main():
    clear_notification()
    hookenv.status_set('active', 'ready')

if __name__ == "__main__":
    main()
