PROJECTPATH = $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

help:
	@echo "This project supports the following targets"
	@echo ""
	@echo " make help - show this text"
	@echo " make test - run the functional test and unittests"
	@echo " make unittest - run the the unittest"
	@echo " make clean - remove unneeded files"
	@echo ""

test: unittest lint

unittest:
	@tox -e unit

clean:
	@echo "Cleaning files"
	@if [ -d $(PROJECTPATH)/.tox ] ; then rm -r $(PROJECTPATH)/.tox ; fi
	@if [ -d $(PROJECTPATH)/.pytest_cache ] ; then rm -r $(PROJECTPATH)/.pytest_cache ; fi

# The targets below don't depend on a file
.PHONY: lint test unittest clean help
