# This is a template `release.yaml` file for ops charms
# This file is managed by bootstack-charms-spec and should not be modified
# within individual charm repos. https://launchpad.net/bootstack-charms-spec

name: Release to Edge

on:
  push:
    branches: [ master, main, dev-release-debug ]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  release:
    needs: check
    steps:
      - name: Placeholder
        run: echo "Release happens here"
